#!/bin/bash
echo "Anzeige der Datei processlist_$(date +%F) mit den aktuell laufenden Prozessen und dem String '$1'" >> processlist_$(date +%F)

if [["$1" == "-h"]]; then
ps -ef | head -1  >> processlist_$(date +%F)
ps -e | grep '$3' >> processlist_$(date +%F)

elif [["$1" == "-n"]]; then
ps -e | grep '$2' >> processlist_$(date +%F)

fi